In [3]:
#question 1
import numpy as np
a=np.array([[1,2,3], [4,5,6] , [7,8,9]])
print(a)
my_list=[]
for i in range(len(a)):
    my_list.append(a[i])
print(my_list)    
    


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [5]:
#question 2
import numpy as np
a=np.array([[1,2,3] , [5,6,7] , [8,9,3]])
result =  np.trace(a)
print("Condition number of the said matrix:")
print(result)

#autre methode


import numpy as np
a=np.array([[1,2,3] , [5,6,7] , [8,9,3]])
for i in range(len(a)):
    print(a[i][i])
    
    


Condition number of the said matrix:
10
1
6
3


In [11]:
#question3
import numpy as np
a=np.array([[1,2] , [3,5]])
x=2
b=a[a>x]
print(b)
    
    

    



[3 5]


In [12]:
# question 4

import numpy as np
A=np.array([[1,2] , [3,4]])
B=np.array([[5,6] , [7,8]])
C=A+B
print(C)


[[ 6  8]
 [10 12]]
